### ISSUE TITLE
优化使用外置grafana和prometheus

### ISSUE THREAD

**Issue by 912988434** [higress-group/higress-console#153]
目前官方的[dashborad](http://higress.io/grafana/dashboard.json) 和 console 中开启的prometheus/grafana 一起用比较匹配，如果使用外置的prometheus+grafana 发现会有下面两个问题：
1、如果用外置的prometheus 加 servicemonitors 抓指标，label就不太一致了，这时候导入dashboard.json 就会异常。
这是自带的prometheus中指标的标签
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/35693221/226510523-e6961815-067b-48e0-a93b-bad248b072eb.png">
这个是通过servicemonitors 抓取到外部prometheus中指标的标签
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/35693221/226510634-ba3ebe8e-7e5e-4de7-bcd9-54a12c028895.png">
可以看到实际上是缺少一些dashboard中 PromQL 需要的label 

2、监控面板这里内嵌使用外置的grafana要改造现有的grafana 开启匿名访问，否则就会页面无法显示

上述两个问题是否考虑优化一下，实际使用中大家应该都是更倾向于复用集群中现有的prometheus/grafana资源。

**Comment by johnlanni** [comment]
@912988434 你的servicemonitor是怎么配置的，按理如果基于pod annotation获取指标的endpoint，label应该是一致的：
![image](https://user-images.githubusercontent.com/6763318/226512355-c7122c4a-6ef8-4f3b-92eb-1e17e2d70502.png)

**Comment by CH3CHO** [comment]
> 监控面板这里内嵌使用外置的grafana要改造现有的grafana 开启匿名访问，否则就会页面无法显示

这个需要麻烦看一下是由于x-frame-options配置的问题还是系统要求登录的问题。

**Comment by 912988434** [comment]
> @912988434你的servicemonitor是怎么配置的，如果基于pod annotation获取指标的endpoint，label应该是一致的： ![图像](https://user-images.githubusercontent.com/6763318/226512355-c7122c4a-6ef8-4f3b-92eb-1e17e2d70502.png)

我之前的ServiceMonitor如下
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hingress
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: higress-gateway
  endpoints:
  - port: metrics
    path: /stats/prometheus
    interval: 30s
  jobLabel: hingress
  namespaceSelector:
    matchNames:
    - higress-system
```
改进了一下ServiceMonitor，现在添加了app和higress这两个label，labels应该差不多了
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hingress
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: higress-gateway
  endpoints:
  - port: metrics
    path: /stats/prometheus
    interval: 30s
    relabelings:
    - regex: '__meta_kubernetes_pod_label_(.+)'
      replacement: '$1'
      action: labelmap
  jobLabel: hingress
  namespaceSelector:
    matchNames:
    - higress-system
```
