### ISSUE TITLE
服务来源支持固定IP和DNS域名

### ISSUE THREAD

**Issue by johnlanni** [higress-group/higress-console#164]
### 固定地址：
多个地址改成逗号分割
![image](https://user-images.githubusercontent.com/6763318/227825978-e3cae8a4-e923-4b41-af12-6ae8a4d27839.png)
### DNS域名：
多个地址改成逗号分隔
![image](https://user-images.githubusercontent.com/6763318/227826008-a24d04af-dc73-444a-ae63-6f3670f58146.png)

### 固定地址:
```yaml
apiVersion: networking.higress.io/v1
kind: McpBridge
metadata:
  name: default
  namespace: higress-system
spec:
  registries:
  - domain: "1.1.1.1:80,2.2.2.2:8080"
    name: my-static-service
    # 服务端口，可以固定 80
    port: 80
    type: static
```
### DNS 域名：
```yaml
apiVersion: networking.higress.io/v1
kind: McpBridge
metadata:
  name: default
  namespace: higress-system
spec:
  registries:
  - domain: "www.baidu.com,www.163.com"
    name: my-dns-service
    port: 80
    type: dns
```
