### ISSUE TITLE
实现域名管理到configmap/secret的模型映射，以及增删改查 API

### ISSUE THREAD

**Issue by johnlanni** [higress-group/higress-console#18]
统一在 higress-system 命名空间下

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: domain-wildcard.abc.com
  namespace: default
data:
  domain: "*.abc.com"
  cert: my-secret
  enableHttps: force
```

名称为domain-开头，后面跟域名，如果出现 * 字符，替换为 wildcard
