### ISSUE TITLE
支持为 Nacos 服务来源配置用户名密码

### ISSUE THREAD

**Issue by CH3CHO** [higress-group/higress-console#246]
## Why do you need it?

为了保证数据安全，Nacos 服务端一般会启用认证功能，要求访问者通过用户名和密码进行认证才能正常的执行服务发现操作。

## How could it be?

McpBridge 已经增加了通过 Secret 来配置用户名密码的功能。可以参考以下的 YAML 配置数据：

```yaml
apiVersion: networking.higress.io/v1
kind: McpBridge
metadata:
  name: default
  namespace: higress-system
spec:
  registries:
    - name: nacos2
      # 注册中心类型是 Nacos 2.x，支持 gRPC 协议
      type: nacos2
      # 注册中心的访问地址，可以是域名或者IP
      domain: 127.0.0.1
      # 注册中心的访问端口，Nacos 默认都是 8848
      port: 8848
      # Nacos 服务分组
      nacosGroups:
        - DEFAULT_GROUP
      authSecretName: higress-nacos-auth
```

```yaml
apiVersion: v1
stringData:
  nacosPassword: higress
  nacosUsername: higress
kind: Secret
metadata:
  name: higress-nacos-auth
  namespace: higress-system
type: Opaque
```

编辑时，界面上默认只需显示认证开启状态。仅在用户需要开启认证的时候才需要显示用户名密码的输入框。

界面示意图：
暂无

## Other related information

- https://github.com/alibaba/higress/pull/445
- API 文档：https://alidocs.dingtalk.com/document/edit?docKey=Wmeonak7mGKVOXxj&dentryKey=oGvjoLvEFr4DKrnJ&type=d
