### ISSUE TITLE
支持配置 Consul 服务来源

### ISSUE THREAD

**Issue by CH3CHO** [higress-group/higress-console#247]
## Why do you need it?

Consul 是一个比较常用的服务注册中心。Higress Controller 已经支持了 Consul，所以控制台也需要具备配置这种服务来源的能力。

## How could it be?

McpBridge 及相关的配置 YAML 格式如下：

```yaml
apiVersion: networking.higress.io/v1
kind: McpBridge
metadata:
  name: default
  namespace: higress-system
spec:
  registries:
    - name: consuldemo
      type: consul
      domain: 192.168.1.1
      port: 8500
      consulDatacenter: dc1
      consulServiceTag: higress
      consulRefreshInterval: 15 # 单位：秒；默认值：30；最小值：10；最大值：600（暂定）
      authSecretName: higress-consul-auth
```

```yaml
apiVersion: v1
stringData:
  consulToken: 4add1665-5394-7c55-23a5-70806d51bc42
kind: Secret
metadata:
  name: higress-consul-auth
  namespace: higress-system
type: Opaque
```

编辑时，界面上默认只需显示认证开启状态。仅在用户需要开启认证的时候才需要显示 Token 输入框。

界面示意图：
暂无

## Other related information

- https://github.com/alibaba/higress/pull/445
- API 文档：https://alidocs.dingtalk.com/document/edit?docKey=Wmeonak7mGKVOXxj&dentryKey=oGvjoLvEFr4DKrnJ&type=d
