### ISSUE TITLE
支持配置 Eureka 服务来源

### ISSUE THREAD

**Issue by CH3CHO** [higress-group/higress-console#250]
## Why do you need it?

Eureka 是一个比较常用的服务注册中心。Higress Controller 已经支持了 Eureka，所以控制台也需要具备配置这种服务来源的能力。

## How could it be?

McpBridge 及相关的配置 YAML 格式如下：

```yaml
apiVersion: networking.higress.io/v1
kind: McpBridge
metadata:
  name: default
  namespace: higress-system
spec:
  registries:
    - name: eurekademo
      type: eureka
      domain: 192.168.1.1
      port: 8761
```

## Other related information

- https://github.com/alibaba/higress/pull/464
- API 文档：https://alidocs.dingtalk.com/document/edit?docKey=Wmeonak7mGKVOXxj&dentryKey=oGvjoLvEFr4DKrnJ&type=d
