### ISSUE TITLE
add securityContext for o11y.prometheus

### ISSUE THREAD

**Issue by OnlyPiglet** [higress-group/higress-console#289]
## Why do you need it?
 Is your feature request related to a problem? Please describe in details

https://github.com/alibaba/higress/issues/727

## How could it be?
A clear and concise description of what you want to happen. You can explain more about input of the feature, and output of it.

add new field for o11y.prometheus to set securityContext for prometheus

```yaml
o11y:
  prometheus:
    securityContext:
      enabled: true
      runAsUser: 0
      fsGroup: 0
```
