### ISSUE TITLE
基于helm部署higress，修改了higress-console values的service.type和service.port之后部署无法访问higress-console

### ISSUE THREAD

**Issue by ishells** [higress-group/higress-console#381]
### Ⅰ. Issue Description
操作步骤
1. 基于Helm拉取higress，修改了charts/higress-console/values.yaml的service.type和service.port分别为LoadBalancer和30080端口（因为通过annotations指定了一个公用的LB，该LB的8080端口已被占用）
```yaml
$ cat charts/higress-console/values.yaml |grep -C 2 service
schedulerName: default-scheduler

service:
  type: LoadBalancer
  port: 30080
```
2. 部署higress，发现无法通过 lb 的 ip + 30080 端口访问higress-console，检查问题后发现higress-console的readnessPorbe没有通过
- 因为higress-console的readnessPorbe监听的是http端口，如下
```yaml
readinessProbe:
   httpGet:
       path: /
       port: http
```
- 同时，higress-console deployemnt的监听端口模板如下：
```yaml
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
```
- 因为deployment的containerPort使用的是{{ .Values.service.port }}字段，一旦service的port被改动了，都会导致higress-console的readnessPorbe无法通过，从而导致访问higress-console有问题

- `使用者会存在修改higress console service port的需求，不应该修改了service的端口就影响到deployment的readnessPorbe，建议将charts/higress-console/templates/deployment.yaml文件的containerPort字段固定为8080，如下`
```yaml
          ports:
            - name: http
              #containerPort: {{ .Values.service.port }}
              containerPort: 8080 
              protocol: TCP

```
