### ISSUE TITLE
使用外部Prometheus问题

### ISSUE THREAD

**Issue by rh-fx** [higress-group/higress-console#411]
## 需要怎么样使用外部Prometheus监控higress

我的操作如下：
照抄根目录下helm下的Prometheus的配置采集了k8s_nodes、k8s_pod，其Prometheus service-discovery查看如下
<img width="1262" alt="Image" src="https://github.com/user-attachments/assets/d820ae5e-3555-4e20-aadc-02aff3d16e35" />
k8s_nodes可以全部active，但是k8s_pod只有4/113
使用的Grafana dash就是市场里面Higress的json import的
<img width="1073" alt="Image" src="https://github.com/user-attachments/assets/07549d05-6e1b-4ef2-8009-cac10ca73efb" />
# prometheus yaml 如下
```yaml
  #node节点发现
  - job_name: 'k8s_nodes'
    kubernetes_sd_configs:
    - role: node
      bearer_token_file: *tokenPath
      api_server: xxxx
      tls_config:
        insecure_skip_verify: true
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - replacement: kubernetes.default.svc:443
        target_label: __address__
      - regex: (.+)
        replacement: /api/v1/nodes/$1/proxy/metrics/cadvisor
        source_labels:
          - __meta_kubernetes_node_name
        target_label: __metrics_path__
    scheme: https
  - job_name: 'k8s_pods'
    kubernetes_sd_configs:
    - role: pod
      api_server: xxxx
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: *tokenPath
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace]
      regex: higress-system
      action: keep
    - source_labels: [__meta_kubernetes_pod_label_app]
      regex: higress-gateway
      action: keep
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
```

**Comment by CH3CHO** [comment]
可以参考一下 Console 里使用的配置：https://github.com/higress-group/higress-console/blob/main/helm/templates/prometheus.yaml

**Comment by rh-fx** [comment]
> 可以参考一下 Console 里使用的配置：https://github.com/higress-group/higress-console/blob/main/helm/templates/prometheus.yaml

没有数据是因为不是网络不通，目前已经解决了。
我有一个新问题是demo里面的有access log的，直接使用dash的json导入的好像没有，应该怎么样可以跟demo一样
demo上的
![Image](https://github.com/user-attachments/assets/18df83db-9ac6-4a37-93ba-f9783024f2f2)
我自己搭的

![Image](https://github.com/user-attachments/assets/1d0a24aa-df6b-4c2b-9bde-be157726f2be)

**Comment by rh-fx** [comment]
> 可以参考一下 Console 里使用的配置：https://github.com/higress-group/higress-console/blob/main/helm/templates/prometheus.yaml

没有完全解决，有部分数据依旧是空的
我的yaml配置
```yaml
  - job_name: 'k8s_pods'
    kubernetes_sd_configs:
    - role: pod
      api_server: xxxx
      tls_config:
        insecure_skip_verify: true
      bearer_token_file: *tokenPath
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace]
      regex: higress-system
      action: keep
    - source_labels: [__meta_kubernetes_pod_label_app]
      regex: higress-gateway
      action: keep
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name
```
项目的yaml配置，`https://github.com/higress-group/higress-console/blob/main/helm/templates/prometheus.yaml`
```yaml
      - job_name: 'k8s_pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          regex: {{ .Release.Namespace }}
          action: keep
        - source_labels: [__meta_kubernetes_pod_label_app]
          regex: higress-gateway
          action: keep
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name
```
![Image](https://github.com/user-attachments/assets/c8ab67da-2c3e-4cdc-9a61-7c4db48e6bea)
