### ISSUE TITLE
Higress console api 和 UI 不支持 wasm plugin 一些功能，如 retryOnFailure 以及 retryOnStatus 的配置

### ISSUE THREAD

**Issue by Colstuwjx** [higress-group/higress-console#489]
## Why do you need it?
有些功能在 CRD 一侧已经支持，但是 higress-console 后端 api 和前端页面还未支持。比如 ai-proxy 插件之前已经支持了 retryOnFailure 和 retryOnStatus ，PR： [higress 1817](https://github.com/alibaba/higress/pull/1817/files) ，但是看 higress console swagger 貌似还不支持

## How could it be?
这块也许可以比如让后端 api 通过 yaml 直接设置的方式支持这类改动，后续前端页面再来实现？

## Other related information
如果 higress-console 不支持这类改动的话，用户需要直接操作 CRD 资源，但是 CRD 资源又搞的非常复杂，wasmplugin \ envoyfilter \ ingress 等，一个功能的实现可能涉及多个 CRD 的改动，对用户来说操作成本非常高

**Comment by CH3CHO** [comment]
retryOnFailure 和 retryOnStatus 这两个 Console 是已经支持了的。你看的是部署好 Console 自己的 swagger 还是观望的 swagger？

![Image](https://github.com/user-attachments/assets/b1ebc280-3eb4-47c9-b1d0-6791f65d548f)

本身 AI 路由就是就是将一系列功能组合到一起提供的一个更傻瓜更便于使用的版本。如果要自己操作 CR 的话，那么可以直接用路由配合相关的 WasmPlugin 配置。这些都是可以实现的。

**Comment by Colstuwjx** [comment]
OK，感谢帮忙确认。有两个问题：

1、界面上看起来不支持单独配置 429 这种状态码做 failover ，不过这块倒是问题不是很大；
2、higress 核心的 CRD 改动和 higress-console 一侧 api / ui 支持，这块有规划过如何对齐吗。可以理解 higress crd 改动会先实现，不过希望是 higress-console 至少会保证能逐步跟上功能，或者提供一个直接设置 json 的 api 来兼容 crd 侧改动也可以

**Comment by CH3CHO** [comment]
> 1、界面上看起来不支持单独配置 429 这种状态码做 failover ，不过这块倒是问题不是很大；

如果有这方面的需求的话，也是可以支持的。只是不光是前端要改，后端生成的 EnvoyFilter 也需要调整。当时做这个功能的时候没有考虑这么多。

> 2、higress 核心的 CRD 改动和 higress-console 一侧 api / ui 支持，这块有规划过如何对齐吗

Console 这边目前社区层面不是特别的活跃，核心贡献者大家事情也比较多，所以迭代肯定会慢一些。Console 在计划上还是提供一些常见功能的配置能力。进阶的需求还没有足够资源去满足。现在 Higress 的大部分功能还都是用 Wasm 插件来实现的。Wasm 插件的配置 API 是比较齐全的。不知道还有哪些需求目前的 API 无法满足呢？

**Comment by Colstuwjx** [comment]
> 不知道还有哪些需求目前的 API 无法满足呢？

就比如这里提到的单独配置 429 支持 retry，其他 4xx 无需支持 retry 这样。

> Console 这边目前社区层面不是特别的活跃，核心贡献者大家事情也比较多，所以迭代肯定会慢一些

非常理解，或者就是可以帮忙提供一篇文档讲解下几个 CRD 之间的协作关系以及 higress-console 后端是如何封装的？我们可以学习下。目前我自己尝试在 UI 配置了以后捞出来了对应 CRD YAML 的内容，说实话，对普通用户的心智负担还是挺重的， 需要写好几个 YAML，涉及 wasmplugin \ mcpbridge \ ingress \ envoyfilter ，写错的话调试起来也比较费劲。

我们希望过一层 higress console 的 API 来降低这个操作成本，但是目前主要问题就是发现 higress-console api 仍然无法 cover 核心功能，还是绕不开要写 CRD YAML。

**Comment by Colstuwjx** [comment]
一方面，我确认了下，这里截图展示的功能是 fallback 功能的实现，还不是我这里提到的 retryOnFailure 和 retryOnStatus ? 我查了下 ai-proxy.internal 的内容， retryOnFailure 设置是没变的，仍然是 false：

```
  defaultConfig:
    providers:
    - apiTokens:
      - XXX
      azureServiceUrl: https://XXX.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2024-08-01-preview
      failover:
        enabled: false
      id: gpt-4o-02
      retryOnFailure:
        enabled: false
      type: azure
```

> 都有哪些核心功能无法覆盖呢？我们可以优先处理一下。

另外，我们关注的核心功能是如下这些：

1. 支持基于一些条件配置额度和限流，会使用到的应该是 ai-token-ratelimit 、ai-quota 插件；
2. 支持基于某些特定 http 状态码做自动重试，会使用到的就是 ai-proxy 的 retryOnFailure retryOnStatus；
3. 在某个 model 节点不可用的时候置为 unhealthy ，相关请求转到另外的健康节点，如果没有健康节点会降级到兜底的节点再尝试请求一次，会用到的就是 ai-proxy 的 failover + fallback 功能；
4. 支持将一些私密信息存储到 secret ，如 model 的 api-key ，用户在 UI 上配置时可以直接通过如 `${secret.default/test-secret.api_key}` 这种格式来配置提取对应 secret 里的 api-key 内容；
5. MCP Server 相关操作也可以通过界面或 console api 来操作

可以帮忙确认或评估下是否可以支持，谢谢大佬！
